openapi: 3.0.4
info:
  title: Transit Planner
  description: |-
    A simple transit planner app based on fixed scheduled

    [View source on Github](https://github.com/corentindautreme/transit-planner)
  contact:
    email: to@do.com
  version: 0.0.1
servers:
  - url: http://localhost:4000
tags:
  - name: lines
    description: Line static data (line code, stops...)
  - name: departures
    description: Departure times
  - name: stops
    description: Stop static data
paths:
  /lines:
    get:
      tags:
        - lines
      summary: List all lines
      description: List all lines
      operationId: getAllLines
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Line'
  /lines/describe-line:
    get:
      tags:
        - lines
      summary: Describe line
      description: Get the details of a line as well as all of its routes, returned as a list of stops and their associated connections grouped by line and direction, given the line's `name`
      operationId: describeLine
      parameters:
        - name: name
          in: query
          description: Line name
          example: '3'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribedLine'
        '400':
          description: Invalid direction for the provided line
        '404':
          description: Stop is not on the provided line
  /lines/describe-route:
    get:
      tags:
        - lines
      summary: Describe line route
      description: Get the route followed by a line as a list of stops and their associated connections, given the line's `name`, and the `direction` of the line
      operationId: describeLineRoute
      parameters:
        - name: name
          in: query
          description: Line name
          example: '3'
          required: true
          schema:
            type: string
        - name: direction
          in: query
          description: Direction of the line
          example: 'Baščaršija'
          required: true
          schema:
            type: string
        - name: from
          in: query
          description: The internal ID of a stop of the line from which to start describing the line
          required: false
          schema:
            type: number
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Stop'
        '400':
          description: The provided stop is not on the provided line, or not served in the provided direction
        '404':
          description: Could not find the provided line, or the provided line exists but doesn't go in the provided direction
  /lines/describe-all:
    get:
      tags:
        - lines
      summary: Describe the routes of each line
      description: Get the details and routes, returned as a list of stops and their associated connections grouped by line and direction, followed by each line of the system
      operationId: describeAllLines
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DescribedLine'
  /departures/scheduled:
    get:
      tags:
        - departures
      summary: Get scheduled departures
      description: Get all scheduled departures for all lines for a given stop, grouped by line and direction
      operationId: getScheduledDepartures
      parameters:
        - name: from
          in: query
          description: Internal ID of the stop
          example: 24
          required: true
          schema:
            type: number
        - name: line
          in: query
          description: Line name
          example: '3'
          required: false
          schema:
            type: string
        - name: direction
          in: query
          description: Direction of the line
          example: 'Ilidža'
          required: false
          schema:
            type: string
        - name: after
          in: query
          description: Time from which departures should be included. Returns all scheduled departures (or the first X scheduled departures, where X is the value set in the `limit` parameter) for the day if not provided
          example: '2025-01-01T07:00:00.000Z'
          required: false
          schema:
            type: string
            format: date-time
        - name: limit
          in: query
          description: Limit the number of departures to be returned for all directions. Returns all scheduled departures (or all departures scheduled after the time set in `after`) for the day if not provided
          example: 5
          required: false
          schema:
            type: number
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeparturesByLine'
  /departures/next:
    get:
      tags:
        - departures
      summary: Get next departures
      description: Get the next immediate departures for all lines for a given stop, grouped by line and direction
      operationId: getNextDepartures
      parameters:
        - name: from
          in: query
          description: Internal ID of the stop
          example: 24
          required: true
          schema:
            type: number
        - name: line
          in: query
          description: Line name
          example: '3'
          required: false
          schema:
            type: string
        - name: direction
          in: query
          description: Direction of the line
          example: 'Ilidža'
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: Limit the number of departures to be returned for all directions. Defaults to 5 if not provided.
          example: 5
          required: false
          schema:
            type: number
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeparturesByLine'
  /stops:
    get:
      tags:
        - stops
      summary: List all stops
      description: List all stops on the network with the lines that serve it (as a list of connections)
      operationId: getAllStops
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Stop"
components:
  schemas:
    Line:
      type: object
      description: A line on the transport network
      properties:
        name:
          type: string
          description: The name of the line
          example: '3'
        type:
          type: string
          description: The type of transport of that line
          enum:
            - tram
            - trolleybus
            - bus
        directions:
          type: array
          items:
            type: string
          description: The directions that the line can take
          example:
            - Baščaršija
            - Ilidža
    Stop:
      type: object
      description: A stop on the transport network
      properties:
        id:
          type: number
          description: An internal ID for the stop
          example: 24
        name:
          type: string
          description: The name of the stop
          example: 'Baščaršija'
        connections:
          type: array
          items:
            $ref: '#/components/schemas/Connection'
    Connection:
      type: object
      description: A connection at a stop
      properties:
        line:
          type: string
          description: The name of the connecting line
          example: '102'
        type:
          type: string
          description: The type of transport of the connecting line
          enum:
            - tram
            - trolleybus
            - bus
          example: trolleybus
        directions:
          type: array
          items:
            type: string
          description: The directions of the connecting line that are reachable at this stop
          example:
            - Otoka
            - Trg Austrije
    Departure:
      type: object
      description: A departure at a stop
      properties:
        scheduledAt:
          type: string
          description: The scheduled time of departure
          format: date-time
          example: '2025-01-01T07:00:00.000Z'
    DeparturesByLine:
      type: object
      description: Departures grouped by line and direction
      additionalProperties:
        type: object
        properties:
          type:
            type: string
            description: The type of transport of the line
            enum:
              - tram
              - trolleybus
              - bus
          departures:
            type: object
            description: Departures for the line grouped by direction
            additionalProperties:
              type: array
              items:
                $ref: "#/components/schemas/Departure"
      example:
        3:
          type: tram
          departures:
            Baščaršija:
              - scheduledAt: "2025-01-01T00:00:00.000Z"
              - scheduledAt: "2025-01-01T00:04:00.000Z"
              - scheduledAt: "2025-01-01T00:08:00.000Z"
            Ilidža:
              - scheduledAt: "2025-01-01T00:00:00.000Z"
              - scheduledAt: "2025-01-01T00:04:00.000Z"
              - scheduledAt: "2025-01-01T00:08:00.000Z"
        103:
          type: trolleybus
          departures:
            Dobrinja:
              - scheduledAt: "2025-01-01T00:00:00.000Z"
              - scheduledAt: "2025-01-01T00:04:00.000Z"
              - scheduledAt: "2025-01-01T00:08:00.000Z"
            Trg Austrije:
              - scheduledAt: "2025-01-01T00:00:00.000Z"
              - scheduledAt: "2025-01-01T00:04:00.000Z"
              - scheduledAt: "2025-01-01T00:08:00.000Z"
    Route:
      type: object
      description: A route taken by a line
      properties:
        direction:
          type: string
          description: The direction of the route
          example: 'Baščaršija'
        stops:
          type: array
          items:
            $ref: '#/components/schemas/Stop'
    DescribedLine:
      type: object
      description: A line on the transport network, including the routes it follows
      properties:
        name:
          type: string
          description: The name of the line
          example: '3'
        type:
          type: string
          description: The type of transport of that line
          enum:
            - tram
            - trolleybus
            - bus
        directions:
          type: array
          items:
            type: string
          description: The directions that the line can take
          example:
            - Baščaršija
            - Ilidža
        routes:
          type: array
          items:
            $ref: '#/components/schemas/Route'
